package main

var SymToCode = map[string]string{
	`؋`:    `AFN`,
	`LEK`:  `ALL`,
	`Ƒ`:    `AWG`,
	`МАН`:  `AZN`,
	`KM`:   `BAM`,
	`$B`:   `BOB`,
	`R$`:   `BRL`,
	`₿`:    `BTC`,
	`P`:    `BWP`,
	`P.`:   `BYN`,
	`BZ$`:  `BZD`,
	`FR.`:  `CHF`,
	`₡`:    `CRC`,
	`KČ`:   `CZK`,
	`RD$`:  `DOP`,
	`€`:    `EUR`,
	`£`:    `GBP`,
	`Q`:    `GTQ`,
	`L`:    `HNL`,
	`KN`:   `HRK`,
	`FT`:   `HUF`,
	`RP`:   `IDR`,
	`₪`:    `ILS`,
	`₹`:    `INR`,
	`J$`:   `JMD`,
	`¥`:    `JPY`,
	`KSH`:  `KES`,
	`៛`:    `KHR`,
	`₩`:    `KRW`,
	`₭`:    `LAK`,
	`₨`:    `LKR`,
	`LS`:   `LVL`,
	`ДЕН`:  `MKD`,
	`₮`:    `MNT`,
	`RM`:   `MYR`,
	`₦`:    `NGN`,
	`C$`:   `NIO`,
	`KR`:   `NOK`,
	`B/.`:  `PAB`,
	`S/.`:  `PEN`,
	`₱`:    `PHP`,
	`ZŁ`:   `PLN`,
	`GS`:   `PYG`,
	`LEI`:  `RON`,
	`ДИН.`: `RSD`,
	`₽`:    `RUB`,
	`S`:    `SOS`,
	`฿`:    `THB`,
	`TT$`:  `TTD`,
	`NT$`:  `TWD`,
	`TSH`:  `TZS`,
	`₴`:    `UAH`,
	`USH`:  `UGX`,
	`$`:    `USD`,
	`$U`:   `UYU`,
	`ЛВ`:   `UZS`,
	`₫`:    `VND`,
	`﷼`:    `YER`,
	`R`:    `ZAR`,
}

var CodeToSym = map[string]struct {
	Name string
	Sym  string
}{
	`AED`: {`UAE Dirham`, ``},
	`AFN`: {`Afghan Afghani`, `؋`},
	`ALL`: {`Albanian Lek`, `LEK`},
	`AMD`: {`Armenian Dram`, ``},
	`ANG`: {`Netherlands Antillean Gulden`, ``},
	`AOA`: {`Angolan Kwanza`, ``},
	`ARS`: {`Argentine Peso`, ``},
	`AUD`: {`Australian Dollar`, ``},
	`AWG`: {`Aruban Florin`, `Ƒ`},
	`AZN`: {`Azerbaijani Manat`, `МАН`},
	`BAM`: {`Bosnia And Herzegovina Konvertibilna Marka`, `KM`},
	`BBD`: {`Barbadian Dollar`, ``},
	`BDT`: {`Bangladeshi Taka`, ``},
	`BGN`: {`Bulgarian Lev`, ``},
	`BHD`: {`Bahraini Dinar`, ``},
	`BIF`: {`Burundi Franc`, ``},
	`BMD`: {`Bermudan Dollar`, ``},
	`BND`: {`Brunei Dollar`, ``},
	`BOB`: {`Bolivian Boliviano`, `$B`},
	`BRL`: {`Brazilian Real`, `R$`},
	`BSD`: {`Bahamian Dollar`, ``},
	`BTC`: {`Bitcoin`, `₿`},
	`BTN`: {`Bhutanese Ngultrum`, ``},
	`BWP`: {`Botswana Pula`, `P`},
	`BYN`: {`New Belarusian Ruble`, `P.`},
	`BYR`: {`Belarusian Ruble`, ``},
	`BZD`: {`Belize Dollar`, `BZ$`},
	`CAD`: {`Canadian Dollar`, ``},
	`CDF`: {`Congolese Franc`, ``},
	`CHF`: {`Swiss Franc`, `FR.`},
	`CLF`: {`Chilean Unit Of Account`, ``},
	`CLP`: {`Chilean Peso`, ``},
	`CNY`: {`Chinese Yuan`, ``},
	`COP`: {`Colombian Peso`, ``},
	`CRC`: {`Costa Rican Colon`, `₡`},
	`CUC`: {`Cuban Convertible Peso`, ``},
	`CUP`: {`Cuban Peso`, ``},
	`CVE`: {`Cape Verdean Escudo`, ``},
	`CZK`: {`Czech Koruna`, `KČ`},
	`DJF`: {`Djiboutian Franc`, ``},
	`DKK`: {`Danish Krone`, ``},
	`DOP`: {`Dominican Peso`, `RD$`},
	`DZD`: {`Algerian Dinar`, ``},
	`EGP`: {`Egyptian Pound`, ``},
	`ERN`: {`Eritrean Nakfa`, ``},
	`ETB`: {`Ethiopian Birr`, ``},
	`EUR`: {`Euro`, `€`},
	`FJD`: {`Fijian Dollar`, ``},
	`FKP`: {`Falkland Islands Pound`, ``},
	`GBP`: {`British Pound`, `£`},
	`GEL`: {`Georgian Lari`, ``},
	`GGP`: {`Guernsey Pound`, ``},
	`GHS`: {`Ghanaian Cedi`, ``},
	`GIP`: {`Gibraltar Pound`, ``},
	`GMD`: {`Gambian Dalasi`, ``},
	`GNF`: {`Guinean Franc`, ``},
	`GTQ`: {`Guatemalan Quetzal`, `Q`},
	`GYD`: {`Guyanese Dollar`, ``},
	`HKD`: {`Hong Kong Dollar`, ``},
	`HNL`: {`Honduran Lempira`, `L`},
	`HRK`: {`Croatian Kuna`, `KN`},
	`HTG`: {`Haitian Gourde`, ``},
	`HUF`: {`Hungarian Forint`, `FT`},
	`IDR`: {`Indonesian Rupiah`, `RP`},
	`ILS`: {`Israeli New Sheqel`, `₪`},
	`IMP`: {`Manx pound`, ``},
	`INR`: {`Indian Rupee`, `₹`},
	`IQD`: {`Iraqi Dinar`, ``},
	`IRR`: {`Iranian Rial`, ``},
	`ISK`: {`Icelandic Króna`, ``},
	`JEP`: {`Jersey Pound`, ``},
	`JMD`: {`Jamaican Dollar`, `J$`},
	`JOD`: {`Jordanian Dinar`, ``},
	`JPY`: {`Japanese Yen`, `¥`},
	`KES`: {`Kenyan Shilling`, `KSH`},
	`KGS`: {`Kyrgyzstani Som`, ``},
	`KHR`: {`Cambodian Riel`, `៛`},
	`KMF`: {`Comorian Franc`, ``},
	`KPW`: {`North Korean Won`, ``},
	`KRW`: {`South Korean Won`, `₩`},
	`KWD`: {`Kuwaiti Dinar`, ``},
	`KYD`: {`Cayman Islands Dollar`, ``},
	`KZT`: {`Kazakhstani Tenge`, ``},
	`LAK`: {`Lao Kip`, `₭`},
	`LBP`: {`Lebanese Lira`, ``},
	`LKR`: {`Sri Lankan Rupee`, `₨`},
	`LRD`: {`Liberian Dollar`, ``},
	`LSL`: {`Lesotho Loti`, ``},
	`LVL`: {`Latvian Lats`, `LS`},
	`LYD`: {`Libyan Dinar`, ``},
	`MAD`: {`Moroccan Dirham`, ``},
	`MDL`: {`Moldovan Leu`, ``},
	`MGA`: {`Malagasy Ariary`, ``},
	`MKD`: {`Macedonian Denar`, `ДЕН`},
	`MMK`: {`Myanma Kyat`, ``},
	`MNT`: {`Mongolian Tugrik`, `₮`},
	`MOP`: {`Macanese Pataca`, ``},
	`MRO`: {`Mauritanian Ouguiya`, ``},
	`MUR`: {`Mauritian Rupee`, ``},
	`MVR`: {`Maldivian Rufiyaa`, ``},
	`MWK`: {`Malawian Kwacha`, ``},
	`MXN`: {`Mexican Peso`, ``},
	`MYR`: {`Malaysian Ringgit`, `RM`},
	`MZN`: {`Mozambican Metical`, ``},
	`NAD`: {`Namibian Dollar`, ``},
	`NGN`: {`Nigerian Naira`, `₦`},
	`NIO`: {`Nicaraguan Cordoba`, `C$`},
	`NOK`: {`Norwegian Krone`, `KR`},
	`NPR`: {`Nepalese Rupee`, ``},
	`NZD`: {`New Zealand Dollar`, ``},
	`OMR`: {`Omani Rial`, ``},
	`PAB`: {`Panamanian Balboa`, `B/.`},
	`PEN`: {`Peruvian Nuevo Sol`, `S/.`},
	`PGK`: {`Papua New Guinean Kina`, ``},
	`PHP`: {`Philippine Peso`, `₱`},
	`PKR`: {`Pakistani Rupee`, ``},
	`PLN`: {`Polish Zloty`, `ZŁ`},
	`PYG`: {`Paraguayan Guarani`, `GS`},
	`QAR`: {`Qatari Riyal`, ``},
	`RON`: {`Romanian Leu`, `LEI`},
	`RSD`: {`Serbian Dinar`, `ДИН.`},
	`RUB`: {`Russian Ruble`, `₽`},
	`RWF`: {`Rwandan Franc`, ``},
	`SAR`: {`Saudi Riyal`, ``},
	`SBD`: {`Solomon Islands Dollar`, ``},
	`SCR`: {`Seychellois Rupee`, ``},
	`SDG`: {`Sudanese Pound`, ``},
	`SEK`: {`Swedish Krona`, ``},
	`SGD`: {`Singapore Dollar`, ``},
	`SHP`: {`Saint Helena Pound`, ``},
	`SLL`: {`Sierra Leonean Leone`, ``},
	`SOS`: {`Somali Shilling`, `S`},
	`SRD`: {`Surinamese Dollar`, ``},
	`STD`: {`Sao Tome And Principe Dobra`, ``},
	`SVC`: {`Salvadoran Colón`, ``},
	`SYP`: {`Syrian Pound`, ``},
	`SZL`: {`Swazi Lilangeni`, ``},
	`THB`: {`Thai Baht`, `฿`},
	`TJS`: {`Tajikistani Somoni`, ``},
	`TMT`: {`Turkmenistan Manat`, ``},
	`TND`: {`Tunisian Dinar`, ``},
	`TOP`: {`Paanga`, ``},
	`TRY`: {`Turkish New Lira`, ``},
	`TTD`: {`Trinidad and Tobago Dollar`, `TT$`},
	`TWD`: {`New Taiwan Dollar`, `NT$`},
	`TZS`: {`Tanzanian Shilling`, `TSH`},
	`UAH`: {`Ukrainian Hryvnia`, `₴`},
	`UGX`: {`Ugandan Shilling`, `USH`},
	`USD`: {`United States Dollar`, `$`},
	`UYU`: {`Uruguayan Peso`, `$U`},
	`UZS`: {`Uzbekistani Som`, `ЛВ`},
	`VEF`: {`Venezuelan Bolivar`, ``},
	`VND`: {`Vietnamese Dong`, `₫`},
	`VUV`: {`Vanuatu Vatu`, ``},
	`WST`: {`Samoan Tala`, ``},
	`XAF`: {`Central African CFA Franc`, ``},
	`XAG`: {`Silver (troy ounce)`, ``},
	`XCD`: {`East Caribbean Dollar`, ``},
	`XDR`: {`Special Drawing Rights`, ``},
	`XOF`: {`West African CFA Franc`, ``},
	`XPF`: {`CFP Franc`, ``},
	`YER`: {`Yemeni Rial`, `﷼`},
	`ZAR`: {`South African Rand`, `R`},
	`ZMK`: {`Old Zambian Kwacha`, ``},
	`ZMW`: {`Zambian Kwacha`, ``},
	`ZWL`: {`Zimbabwean Dollar`, ``},
}

var Codes = []string{`AED`, `AFN`, `ALL`, `AMD`, `ANG`, `AOA`, `ARS`, `AUD`, `AWG`, `AZN`, `BAM`, `BBD`, `BDT`, `BGN`, `BHD`, `BIF`, `BMD`, `BND`, `BOB`, `BRL`, `BSD`, `BTC`, `BTN`, `BWP`, `BYN`, `BYR`, `BZD`, `CAD`, `CDF`, `CHF`, `CLF`, `CLP`, `CNY`, `COP`, `CRC`, `CUC`, `CUP`, `CVE`, `CZK`, `DJF`, `DKK`, `DOP`, `DZD`, `EGP`, `ERN`, `ETB`, `EUR`, `FJD`, `FKP`, `GBP`, `GEL`, `GGP`, `GHS`, `GIP`, `GMD`, `GNF`, `GTQ`, `GYD`, `HKD`, `HNL`, `HRK`, `HTG`, `HUF`, `IDR`, `ILS`, `IMP`, `INR`, `IQD`, `IRR`, `ISK`, `JEP`, `JMD`, `JOD`, `JPY`, `KES`, `KGS`, `KHR`, `KMF`, `KPW`, `KRW`, `KWD`, `KYD`, `KZT`, `LAK`, `LBP`, `LKR`, `LRD`, `LSL`, `LVL`, `LYD`, `MAD`, `MDL`, `MGA`, `MKD`, `MMK`, `MNT`, `MOP`, `MRO`, `MUR`, `MVR`, `MWK`, `MXN`, `MYR`, `MZN`, `NAD`, `NGN`, `NIO`, `NOK`, `NPR`, `NZD`, `OMR`, `PAB`, `PEN`, `PGK`, `PHP`, `PKR`, `PLN`, `PYG`, `QAR`, `RON`, `RSD`, `RUB`, `RWF`, `SAR`, `SBD`, `SCR`, `SDG`, `SEK`, `SGD`, `SHP`, `SLL`, `SOS`, `SRD`, `STD`, `SVC`, `SYP`, `SZL`, `THB`, `TJS`, `TMT`, `TND`, `TOP`, `TRY`, `TTD`, `TWD`, `TZS`, `UAH`, `UGX`, `USD`, `UYU`, `UZS`, `VEF`, `VND`, `VUV`, `WST`, `XAF`, `XAG`, `XCD`, `XDR`, `XOF`, `XPF`, `YER`, `ZAR`, `ZMK`, `ZMW`, `ZWL`}
